=== zzt93/SqlCreator/src/main/java/io/transwarp/parse/xml/define.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tests">
        <xs:complexType>
            <xs:all>
                <xs:element name="test" type="sql" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="sql">
        <xs:all>
            <xs:element name="query" type="selectStmt" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="updateStmt" type="updateStmt" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="deleteStmt" type="deleteStmt" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="createStmt" type="createStmt" minOccurs="0" maxOccurs="unbounded"/>
        </xs:all>
        <xs:attribute name="transaction" type="xs:boolean" default="false"/>
        <xs:attribute name="threads" type="xs:unsignedInt" default="2"/>
        <xs:attribute name="dialect" type="xs:string" default="oracle"/>
        <xs:attribute name="table" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="stmt">
        <xs:attribute name="ref" type="stmt"/>
    </xs:complexType>
    <xs:complexType name="selectStmt">
        <xs:sequence>
            <xs:element name="select" type="operator" minOccurs="0"/>
            <xs:element name="from" type="from" minOccurs="0"/>
            <xs:element name="where" type="operator" minOccurs="0"/>
            <xs:element name="group-by" type="operator" minOccurs="0"/>
            <xs:element name="having" type="operator" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="depth" type="xs:int" default="1"/>
        <xs:attribute name="table" type="xs:string" default="default_oracle.sql"/>
        <xs:attribute name="dialect" type="dialects" default="oracle"/>
        <xs:attribute name="num" type="xs:int" default="100"/>
        <xs:attribute name="ref" type="selectStmt"/>
        <xs:attribute name="nested-query-depth" type="xs:int" default="1"/>
    </xs:complexType>

    <xs:complexType name="updateStmt">

    </xs:complexType>
    <xs:complexType name="deleteStmt">

    </xs:complexType>
    <xs:complexType name="createStmt">

    </xs:complexType>

    <xs:complexType name="operator">
        <xs:all>
            <xs:element name="operand" type="operand" maxOccurs="unbounded" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="operand">
        <xs:all>
            <xs:element name="const" minOccurs="0" maxOccurs="1"/>
            <xs:element name="expr" type="operand" minOccurs="0" maxOccurs="1"/>
            <xs:element name="query" type="selectStmt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="operand" type="operand" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute name="udf"/>
        <xs:attribute name="udf-depth" default="3"/>
        <xs:attribute name="desc"/>
    </xs:complexType>

    <xs:complexType name="from">
        <xs:all>
            <xs:element name="join" type="operator"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="dialects" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="oracle" />
            <xs:enumeration value="inceptor" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== zzt93/SqlCreator/src/test/resources/xsdValidationError.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="define.xsd">

    <test>

        <query id="testJoin1">
            <select/>
            <from>
                <join>
                    <operand/>
                </join>
            </from>
        </query>
        <query id="testJoin2">
            <select/>
            <from>
                <join>
                    <operand/>
                    <operand/>
                </join>
            </from>
        </query>
        <query id="testJoin3">
            <select/>
            <from>
                <join>
                    <operand/>
                    <operand/>
                    <condition/>
                </join>
            </from>
        </query>

        <query id="testJoin10">
            <select/>
            <from>
                <implicitJoin/>
            </from>
        </query>

        <query id="testJoin15">
            <select/>
            <from>
                <implicitJoin>
                    <operand>
                        <tableName>test_udf_2</tableName>
                    </operand>
                    <operand>
                        <tableName>test_udf</tableName>
                    </operand>
                    <condition/>
                </implicitJoin>
            </from>
        </query>
    </test>

</tests>

=== zzt93/SqlCreator/src/main/java/io/transwarp/parse/xml/test.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="define.xsd">
    <test>
        <query id="nonEqualJoin">
            <from>
                <join>
                    <operand desc="default: table or query"/>
                    <operand>
                        <query depth="2" ref="simpleQuery"/>
                    </operand>
                    <operand desc="condition" udf="and">
                        <expr udf="=" udf-depth="1"/>
                        <operand desc="default: const/expr/operand"/>
                    </operand>
                </join>
            </from>
        </query>
        <query id="simpleQuery"/>
    </test>


    <test>
        <query num="1000">
            <!--specify needed keyword-->
            <group-by/>
            <having/>
        </query>
    </test>


    <!--transaction default value is false-->
    <test transaction="true" threads="3">
    </test>





</tests>
